---

is_debug: true
token:
  ACCESS_TOKEN_PRIVATE_KEY: 123
  ACCESS_TOKEN_PUBLIC_KEY: 123
  REFRESH_TOKEN_PRIVATE_KEY: 123
  REFRESH_TOKEN_PUBLIC_KEY: 123
  ACCESS_TOKEN_EXPIRED_IN: 5m
  REFRESH_TOKEN_EXPIRED_IN: 3600m