name: Build

on:
  push:
    branches: [master]

jobs:
  fileserver_build:
    runs-on: ubuntu-latest
    container: golang:1.19

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build fileserver
        run: |
          cd fileserver/cmd
          go build -o filserver -buildvcs=false

  filserver_test:
    needs: [fileserver_build]
    runs-on: ubuntu-latest
    container: golang:1.19

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Test fileserver
        run: |
          go test fileserver/... -cover

  filserver_lint:
    needs: [fileserver_build]
    runs-on: ubuntu-latest
    container: golang:1.19

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build linter
        run: |
          cd linter/cmd
          go build -o linter -buildvcs=false
          ./linter ../

      - name: lint fileserver
        run: |
          go vet -vettool=$(which statictest) fileserver/...

  cliclient_build:
    runs-on: ubuntu-latest
    container: golang:1.19

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build cliclient
        run: |
          cd cliclient/cmd
          go build -o cliclient -buildvcs=false

  cliclient_test:
    needs: [cliclient_build]
    runs-on: ubuntu-latest
    container: golang:1.19

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Test cliclient
        run: |
          go test cliclient/... -cover

  cliclient_lint:
    needs: [cliclient_build]
    runs-on: ubuntu-latest
    container: golang:1.19

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: lint cliclient
        run: |
          go vet -vettool=$(which statictest) cliclient/...

  authserver_build:
    runs-on: ubuntu-latest
    container: golang:1.19

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build authserver
        run: |
          cd authserver/cmd
          go build -o authserver -buildvcs=false

  authserver_test:
    needs: [authserver_build]
    runs-on: ubuntu-latest
    container: golang:1.19

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Test authserver
        run: |
          go test authserver/... -cover

  authserver_lint:
    needs: [authserver_build]
    runs-on: ubuntu-latest
    container: golang:1.19

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: lint authserver
        run: |
          go vet -vettool=$(which statictest) authserver/...

  keepserver_build:
    runs-on: ubuntu-latest
    container: golang:1.19

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build keepserver
        run: |
          cd keepserver/cmd/keepserver
          go build -o keepserver -buildvcs=false

  keepserver_migration:
    needs: [keepserver_build]
    runs-on: ubuntu-latest
    container: golang:1.19

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build migrations
        run: |
          cd keepserver/cmd/migrations
          go build -o keepmigration  -buildvcs=false

      - name: Start migration
        run: |
          ./keepmigration

  keepserver_test:
    needs: [keepserver_build]
    runs-on: ubuntu-latest
    container: golang:1.19

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Test keepserver
        run: |
          go test keepserver/... -cover

  keepserver_lint:
    needs: [keepserver_build]
    runs-on: ubuntu-latest
    container: golang:1.19

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: lint keepserver
        run: |
          go vet -vettool=$(which statictest) keepserver/...